### ISSUE TITLE
payment info does not update properly

### ISSUE THREAD

**Issue by ujwal2003** [ujwal2003/Software-Design-Project#46]
__Description:__  
For new accounts, or accounts that did not have payment info initially set up the update button does not update (or set) any payment information. Once hitting submit the fields return to being empty.

This only seems to be an issue with accounts that did not already have payment info set, for accounts that had payment info in the dummy data already the update for payment info works perfectly.

**Comment by yonatandeneke** [comment]
...spent 2 hours looking for 1 missing line of code

.......................................................................................
