### ISSUE TITLE
app freezes when clicking receipts

### ISSUE THREAD

**Issue by ujwal2003** [ujwal2003/Software-Design-Project#47]
__Description:__  
App freezes when clicking 'payment details' for a new or recently purchased quotes. This problem does not appear for receipts that already existed from dummy data, only when new receipts are made after a purchase has been made.

The problem causes the page to freeze and no navigation buttons to work, the app has to be refreshed to navigate to another page.

**Comment by yonatandeneke** [comment]
fixed, quoteID wasnt being stored in purchaseHistory
