### ISSUE TITLE
quote form redirects to login when user has no profile

### ISSUE THREAD

**Issue by ujwal2003** [ujwal2003/Software-Design-Project#50]
__Description:__
User is displayed an error modal (saying user should log in again) and then redirected to login page when going to quote form page if said user has no profile set.

__Expected Behavior:__  
Error should ask user to set profile info and redirect to profile page

**Comment by yonatandeneke** [comment]
fixed by checking if profile is filled out by the client already, if not then it does not let the user proceed to create a quote
