### ISSUE TITLE
generation dates of new quotes are of the next day

### ISSUE THREAD

**Issue by ujwal2003** [ujwal2003/Software-Design-Project#58]
__Description:__  
When a new quote is generated the 'Generation Date' field in the table shows the date of the next day instead of the day the quote was generated on.

**Comment by yonatandeneke** [comment]
wasn't able to recreate the issue, did you already fix it?

**Comment by ujwal2003** [comment]
Was not intending to fix it but it seems while connecting the database with the rest of the code I may have accidentally fixed it. Thanks for pointing that out, I'll close this issue.
